#!/bin/bash

host_ip="head.ouetag.org"

#Mongo Data Node
echo "************** Mongo Data Node ***********"
docker run -d --net=host -v /opt/risser_etag/mongo:/data/db mongo # cybercom/mongo-datanode
#docker run -d --net=host  mongo --smallfiles #cybercom/mongo-datanode
#Rabbitmq
echo "************** Rabbitmq        ***********"
docker run -d -p 5672:5672 -p 15672:15672 rabbitmq #cybercom/rabbitmq
#wait for container
sleep 5
echo "************** Setup Rabbitmq  ***********"
container=$(docker ps | grep rabbitmq | awk '{print $1}')
source /opt/risser_etag/risser/config.sh
docker exec -t $container rabbitmqctl add_user ${user} ${password}
docker exec -t $container rabbitmqctl add_vhost ${vhost}
docker exec -t $container rabbitmqctl set_permissions -p ${vhost} ${user} ".*" ".*" ".*"

#Celery
echo "********** Celery Async Queue ************"
docker run -d --net=host -v /home/mstacy/.ssh:/root/.ssh -v /opt/risser_etag/celery/code:/code -v /opt/risser_etag/celery/log:/log -v /opt/risser_etag/data:/data -e "docker_worker=$host_ip" -e "docker_username=mstacy"  -e "C_FORCE_ROOT=true" -e "CELERY_CONCURRENCY=2" cybercom/celery
sleep 5
echo "********* Requires wget ************"
container=$(docker ps | grep celery | awk '{print $1}')
docker exec -it $container apt-get install wget

#API
echo "*********  API       *********************"
docker run -d  --net=host -v /opt/risser_etag/etagapi:/usr/src/app -v /opt/risser_etag/config/api_config.py:/usr/src/app/api/config.py -v /opt/risser_etag/config/db.sqlite3:/usr/src/app/db.sqlite3 -v /data:/data -v /home/mstacy/.ssh:/root/.ssh api_etag

#Ngnix
echo "********* Ngnix       ********************"
docker run --net=host -v /data:/data -v /opt/risser_etag/nginx/nginx.conf:/etc/nginx/nginx.conf -v /opt/risser_etag/nginx/default.conf:/etc/nginx/conf.d/default.conf -d nginx
#-p 80:80  nginx

#Clear memcache
echo "******** Clearing Memcache ***************"
echo 'flush_all' | nc {{memcache_host}} {{memcache_port}}
