#!/bin/bash

host_ip="{{cookiecutter.docker_worker}}"

#Mongo Data Node
echo "************** Mongo Data Node ***********"
docker run -d --net=host -v {{cookiecutter.docker_host_data_directory}}/{{cookiecutter.application_short_name}}/data/mongo:/data/db mongo # cybercom/mongo-datanode
#docker run -d --net=host  mongo --smallfiles #cybercom/mongo-datanode
#Rabbitmq
echo "************** Rabbitmq        ***********"
docker run -d -p 5672:5672 -p 15672:15672 rabbitmq #cybercom/rabbitmq
#wait for container
sleep 5
echo "************** Setup Rabbitmq  ***********"
container=$(docker ps | grep rabbitmq | awk '{print $1}')
source /opt/risser_etag/risser/config.sh
docker exec -t $container rabbitmqctl add_user ${user} ${password}
docker exec -t $container rabbitmqctl add_vhost ${vhost}
docker exec -t $container rabbitmqctl set_permissions -p ${vhost} ${user} ".*" ".*" ".*"

#Celery
echo "********** Celery Async Queue ************"
docker run -d --net=host -v {{cookiecutter.user_home}}/.ssh:/root/.ssh -v {{cookiecutter.docker_host_data_directory}}/{{cookiecutter.application_short_name}}/data/celery/code:/code -v {{cookiecutter.docker_host_data_directory}}/{{cookiecutter.application_short_name}}/celery/log:/log -v {{cookiecutter.docker_host_data_directory}}/{{cookiecutter.application_short_name}}/data:/data -e "docker_worker=$host_ip" -e "docker_username={{cookiecutter.docker_username}}"  -e "C_FORCE_ROOT=true" -e "CELERY_CONCURRENCY={{cookiecutter.celery_concurrency}}" cybercom/celery
sleep 5
echo "********* Requires wget ************"
container=$(docker ps | grep celery | awk '{print $1}')
docker exec -it $container apt-get install wget

#API
echo "*********  API       *********************"
docker run -d  --net=host -v {{cookiecutter.docker_host_data_directory}}/{{cookiecutter.application_short_name}}/risser_api:/usr/src/app -v {{cookiecutter.docker_host_data_directory}}/{{cookiecutter.application_short_name}}/config/api_config.py:/usr/src/app/api/config.py -v {{cookiecutter.docker_host_data_directory}}/{{cookiecutter.application_short_name}}/config/db.sqlite3:/usr/src/app/db.sqlite3 -v {{cookiecutter.docker_host_data_directory}}/{{cookiecutter.application_short_name}}/data:/data  api

#Ngnix
echo "********* Ngnix       ********************"
docker run --net=host -v {{cookiecutter.docker_host_data_directory}}/{{cookiecutter.application_short_name}}/data:/data -v {{cookiecutter.docker_host_data_directory}}/{{cookiecutter.application_short_name}}/nginx/nginx.conf:/etc/nginx/nginx.conf -v {{cookiecutter.docker_host_data_directory}}/{{cookiecutter.application_short_name}}/nginx/default.conf:/etc/nginx/conf.d/default.conf -d nginx
#-p 80:80  nginx

#Clear memcache
echo "******** Clearing Memcache ***************"
echo 'flush_all' | nc {{memcache_host}} {{memcache_port}}
