#!/bin/bash
source ../config/config.sh

MONGO_CONTAINER={{cookiecutter.application_short_name}}_mongo
MONGO_VOLUME={{cookiecutter.application_short_name}}_mongodata

RUNNING=$(docker inspect --format="{{.State.Running}}" $MONGO_CONTAINER 2> /dev/null)

if [ "$RUNNING" == "true" ]; then
  docker exec -it $MONGO_CONTAINER \
    mongo admin --ssl \
    --sslPEMKeyFile /ssl/client/mongodb.pem \
    --sslCAFile /ssl/testca/cacert.pem \
    --sslAllowInvalidHostnames \
    --username $mongo_username \
    --password $mongo_password
else
  docker run -it --rm \
    -v $MONGO_VOLUME:/data/db:z \
    mongo sh -c "mongod --fork --logpath --quiet && mongo admin"
fi
