#!/bin/bash

#Kill only namespace docker container and remove containers
docker ps |grep {{cookiecutter.application_short_name}} | awk '{print $1}'| xargs docker kill 
docker ps -a | grep {{cookiecutter.application_short_name}}| awk '{print $1}' | xargs docker rm 
#sudo service docker stop
#sudo service docker start
