#!/bin/bash

#generate keys for nginx
{% if cookiecutter.ssl_self_signed != 'y' %}# SSL has not been configured for nginx - to force generation of keys, uncomment the following lines:{% endif %}
{% if cookiecutter.ssl_self_signed != 'y' %}#{% endif %}docker run -it --rm --name {{cookiecutter.application_short_name}}_openssl \
{% if cookiecutter.ssl_self_signed != 'y' %}#{% endif %}  -v {{cookiecutter.docker_host_data_directory}}/{{cookiecutter.application_short_name}}/config/ssl/nginx:/sslnginx:z \
{% if cookiecutter.ssl_self_signed != 'y' %}#{% endif %}  nginx ./sslnginx/generate

#generate keys for message broker and clients
docker run -it --rm --name {{cookiecutter.application_short_name}}_openssl \
  -v {{cookiecutter.docker_host_data_directory}}/{{cookiecutter.application_short_name}}/config/ssl/rabbitmq:/sslrabbitmq \
  nginx ./sslrabbitmq/generate

