#!/bin/bash

docker run -it --rm \
  -v {{cookiecutter.application_install_directory}}/{{cookiecutter.application_short_name}}/config/ssl/nginx/letsencrypt/entrypoint.sh:/entrypoint.sh \
  -v {{cookiecutter.application_install_directory}}/{{cookiecutter.application_short_name}}/config/ssl/nginx/letsencrypt/etc:/etc/letsencrypt:z \
  -v {{cookiecutter.application_install_directory}}/{{cookiecutter.application_short_name}}/config/ssl/nginx/letsencrypt/www:/www:z \
  --entrypoint=/entrypoint.sh \
  centos

