#!/bin/bash

# This script is called inside a mongo container to create / udpate user account

# Pull in config
source /config.sh

/usr/bin/mongod &

sleep 5

if [ ! -z ${mongo_admin_username+x} ]
  then
    echo "<<<<<<<<<< Adding Admin User >>>>>>>>>"
    mongo admin --eval "db.createUser({ user: '$mongo_admin_username', pwd: '$mongo_admin_password', roles: [ { role: '$mongo_admin_role', db: 'admin' } ] });"

    if [ $? == 252 ]
      then
        echo "<<<<<<<<<< Admin User Exists - Updating >>>>>>>>>" 
        mongo admin --eval "db.updateUser('$mongo_admin_username', { pwd: '$mongo_admin_password', roles: [ { role: '$mongo_admin_role', db: 'admin' } ] });"
    fi
fi

echo "<<<<<<<<<< Adding Mongo User >>>>>>>>>"
mongo admin --eval "db.createUser({ user: '$mongo_username', pwd: '$mongo_password', roles: [ { role: 'dbAdminAnyDatabase', db: 'admin' }, { role: 'readWriteAnyDatabase', db: 'admin' } ] });"

if [ $? == 252 ]
  then
    echo "<<<<<<<<<< User Already Exists - Updating >>>>>>>>>" 
    mongo admin --eval "db.updateUser('$mongo_username', { pwd: '$mongo_password', roles: [ { role: 'dbAdminAnyDatabase', db: 'admin' }, { role: 'readWriteAnyDatabase', db: 'admin' } ] });"
fi

/usr/bin/mongod --shutdown
